from gtl_port.gap import *

print(f"GAP_AUTH.GAP_AUTH_REQ_NO_MITM_NO_BOND={GAP_AUTH.GAP_AUTH_REQ_NO_MITM_NO_BOND}")
print(f"GAP_AUTH.GAP_AUTH_REQ_NO_MITM_BOND={GAP_AUTH.GAP_AUTH_REQ_NO_MITM_BOND}")
print(f"GAP_AUTH.GAP_AUTH_REQ_MITM_NO_BOND={GAP_AUTH.GAP_AUTH_REQ_MITM_NO_BOND}")
print(f"GAP_AUTH.GAP_AUTH_REQ_MITM_BOND={GAP_AUTH.GAP_AUTH_REQ_MITM_BOND}")
print(f"GAP_AUTH.GAP_AUTH_REQ_SECURE_CONNECTION={GAP_AUTH.GAP_AUTH_REQ_SECURE_CONNECTION}")
print(f"GAP_AUTH.GAP_AUTH_REQ_KEYPRESS_NOTIFICATIONS={GAP_AUTH.GAP_AUTH_REQ_KEYPRESS_NOTIFICATIONS}")