# RWBT SW Major Version
RWBLE_SW_VERSION_MAJOR = 8
# RWBT SW Minor Version
RWBLE_SW_VERSION_MINOR = 1  # CSSv6, ESR10
# RWBT SW Build Version
RWBLE_SW_VERSION_BUILD = 15
# RWBT SW Major Version
RWBLE_SW_VERSION_SUB_BUILD = 0
